# Setup
title:               Rahul's
tagline:             'Personal Blog'
description:         'Welcome To My Digital Garden.'
url:                 https://bansalrahul.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Rahul Bansal
  url:               https://twitter.com/BansalRahul14
  email:             bansal.rahul14@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: YBXG5G3E48
